apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    run: mypod
spec:
  containers:
    - image: /var/lib/docker/examplenode
      name: haroon-app
      ports:
        - containerPort: 3000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
